### ISSUE TITLE
Lack of misuse resistance in Pointcheval Sanders API

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/libzkchannels-crypto#25]
https://github.com/boltlabs-inc/libzkchannels-crypto/blob/3d529249ac9f37a77d8eba8d2bad01c7b3c46d26/libzkchannels-crypto/src/ps_blind_signatures.rs#L107

The comments indicate that `try_blind_sign` should be used "judiciously", but make it sound like performing a PoK of the opening of the blinded message is an example of judicious usage. However, I believe it is required for correctness to do _at least_ a PoK of opening of the blinded message, and there are possible security implications as well.

I am also concerned there are other implications with respect to security when signing certain messages, e.g., perhaps you could get back a signature not just on a message you don't know, but one that reveals useful information about the signer's private key. This concern is more obvious in the context of blind PS signatures, but is not absent from regular PS signatures.

My inclination is to either improve the documentation to clarify requirements for correct usage of the scheme, or modify the API to make misuse harder. We should consider creating a separate issue looking at edge case messages in PS signatures and hardening our implementation against them.

- [x] Design API for SignatureRequestProof
- [x] Integrate API into zkAbacus (#153)
- [x] Implement `SignatureRequestProof` API
