### ISSUE TITLE
zkChannels implementation (abacus + tezos escrow)

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/libzkchannels-crypto#87]
The zkChannels module integrates two pieces of the protocol: zkAbacus (the off-chain logic) and zkEscrowAgent AKA tezos mid-layer API (the on-chain logic).

Roughly, this has several steps (todo: break these into more specific issues)
- [ ] dialectic type for zkChannels Establish
- [ ] dialectic type for zkChannels Pay
- [ ] dialectic type for zkChannels Close
- [ ] Customer: establish
- [ ] Merchant: establish
- [ ] Customer: pay
- [ ] Merchant: pay
- [ ] Customer: close
- [ ] Merchant: close

This is a long list, but it does not contain too much logic, since all the hard stuff is contained in abacus and escrow agent.
